### PR TITLE
Making sure our certs are up to date before running the hipchat tasks

### PR DESCRIPTION
**Pull request by rafecolton**
otherwise it may complain that it cannot verify them

### CODE REVIEW

**Comment by jszwedko** [comment]
Hmm, should this just be part of bootstrapping?

**Comment by rafecolton** [comment]
Meh.  Either way I would want to update them (ala `update-ca-certificates --fresh`) before depending on them, so it doesn't really buy us anything to do it during bootstrap

**edit:** That being said, it probably wouldn't hurt to do it there too

**Comment by jszwedko** [comment]
I guess I was mostly feeling that this was just a system responsibility (i.e. bootstrap) to make sure certs are up to date. If they fall out of date, users should re-bootstrap their systems (we could even do that with ansible pull if we really wanted...).

**Comment by jszwedko** [comment]
Or a cronjob that updated certs

**Comment by rafecolton** [comment]
@jszwedko I place it in the same category as `apt-get update` in that it is technically a system concern, but practically speaking, we need to run it before we depend on it.

**edit:** that being said, I don't think I've ever had to run it on a given machine more than once

**Comment by jszwedko** [comment]
Hmm, well at least we have 3 people now so we can have a majority! :smile_cat: How do you feel @alexschlessinger ?

**Comment by alexschlessinger** [comment]
I agree this is a bootstrap/system concern. And we should make damn sure
bootstrap is 100% idempotent :)

**Comment by rafecolton** [comment]
:+1: closed by https://github.com/modcloth/ansible-role-bootstrap/pull/52

**Pull request closed without merging**
