### PR TITLE
Allow mounting of file volumes

### PR DESCRIPTION
**Pull request by rafecolton**
Addresses https://github.com/modcloth/ansible-role-modcloth-app/issues/21

### CODE REVIEW

**Comment by jszwedko** [comment]
I kind of liked the README automation so we don't worry about them getting out of sync.

**Comment by jszwedko** [comment]
:shipit: otherwise

**Comment by jszwedko** [comment]
:( to the README automation removal

**Comment by rafecolton** [comment]
It seemed like an unreasonable amount of complexity for such a simple thing, plus I feel like it discourages people from updating the actual README.  It also didn't seem reasonable for it to causes tests to fail.

**Pull request merged**
