### PR TITLE
[DO NOT MERGE] Allow env vars to be defined and empty when passed into the container

### PR DESCRIPTION
**Pull request by rafecolton**
(otherwise, they will be defaulted to 'None' if left blank)

### CODE REVIEW

**Comment by rafecolton** [comment]
Marking this as DO NOT MERGE - I will submit another pull request without all of the travis debugging commits.  @jszwedko @meatballhat any idea if something changed on travis that would cause the example playbook to no longer be able to use `sudo`?  The test failure doesn't seem to have anything to do with the change...

**Comment by jszwedko** [comment]
Looks like we are running on the new docker Travis CI infrastructure:

`Using worker: worker-linux-docker-2432e5c5.prod.travis-ci.org:travis-linux-12`

which doesn't allow sudo.

**Comment by jszwedko** [comment]
I think you just need to set `sudo: true` in the `.travis.yml`.

**Comment by rafecolton** [comment]
@jszwedko so it is, thanks!  Submitting a separate pr for this

**Pull request closed without merging**
