### PR TITLE
Add ability to pipe STDIN to cron tasks

### PR DESCRIPTION
**Pull request by jszwedko**
In case the container expects input.

Signed-off-by: Dan Buch d.buch@modcloth.com

### CODE REVIEW

**Comment by rafecolton** [comment]
I'm not sure this should be in here.  Maybe it would be better for the apps should just accept command line arguments?

**Comment by jszwedko** [comment]
I'm not sure about the limitations of command line arguments are, but we expect to see streams on the order of 10k values. Converting the output of the piped command to command line arguments may not be terribly efficient.

**Comment by meatballhat** [comment]
:shipit: this is a valid use case, IMHO.  We're doing it more than twice.  It's not very invasive.

**Comment by rafecolton** [comment]
Could you maybe include a blurb describing the use case?  Then I'm all :shipit:

**Comment by alexschlessinger** [comment]
:shipit: modulo dem merge conflicts.

**Pull request merged**
