### PR TITLE
Adding modcloth.rsyslog-file to deps for vagrant testing and such

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by rafecolton** [comment]
Is it possible to achieve this same effect by setting it as a dependency in `meta/main.yml`?  Or does that not actually pull it down

**Comment by meatballhat** [comment]
@rafecolton doesn't pull it down, AFAICT

**Comment by meatballhat** [comment]
@rafecolton I should say, it doesn't pull it down when _this_ role is locally already available.

**Comment by rafecolton** [comment]
Gotcha

:shipit:

**Pull request merged**
